config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from two_factor.urls import urlpatterns as tf_urls
from two_factor.views import LoginView

urlpatterns = [
    path('account/login/', LoginView.as_view(redirect_authenticated_user=True), name='two_factor:login'),
    path('', include(tf_urls)),
    path('admin/', admin.site.urls),
    path('tarefas/', include('tarefas.urls')),
    path('core/', include('core.urls')),    
    path('entretenimentos/', include('entretenimentos.urls')),
    path('', RedirectView.as_view(pattern_name='pagina_inicial', permanent=False)),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('pagina-inicial/', views.pagina_inicial, name='pagina_inicial'),
    path('perfil/', views.visualizar_perfil, name="perfil")
]

entretenimentos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.entretenimento_list, name='entretenimento_list'),
    path('novo-entretenimento/', views.entretenimento_create, name='entretenimento_create'),
    path('<int:id_entretenimento>/', views.entretenimento_detail, name="entretenimento_detail"),
    path('delete/<int:id_entretenimento>/', views.entretenimento_delete, name="entretenimento_delete") 
]

entretenimentos/models.py
from django.db import models
from core.models import CustomUser
from django.utils import timezone

# Create your models here.
class Entretenimento(models.Model):
    class Tipo(models.TextChoices):
        FILME = 'FILME', 'Filme'
        SERIE = 'SERIE', 'Série'
        LIVRO = 'LIVRO', 'Livro'
        JOGO = 'JOGO', 'Jogo'
        CULTURA = 'CULTURA', 'Cultura'
    
    class Status(models.TextChoices):
        PENDENTE = 'PENDENTE', 'Pendente'
        ANDAMENTO = 'ANDAMENTO', 'Andamento'
        CONCLUIDO = 'CONCLUIDO', 'Concluído'
    
    criado_em = models.DateTimeField(auto_now_add=True)
    tipo = models.CharField(max_length=10, choices=Tipo.choices, verbose_name='Tipo')
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.PENDENTE)
    iniciado_em = models.DateTimeField(null=True, blank=True, editable=False)
    finalizado_em = models.DateTimeField(null=True, blank=True, editable=False)
    criado_por = models.ForeignKey(CustomUser, on_delete=models.CASCADE, editable=False)

    def __str__(self):
        return self.descricao
    
    def save(self, *args, **kwargs):
        # verificações de status para atualizações atumáticas
        if self.status == Entretenimento.Status.CONCLUIDO:
            self.finalizado_em = timezone.now()
            if self.iniciado_em is None:
                self.iniciado_em = timezone.now()
        if self.status != Entretenimento.Status.CONCLUIDO:
            self.finalizado_em = None
            if self.status == Entretenimento.Status.PENDENTE:
                self.iniciado_em = None
        if self.status == Entretenimento.Status.ANDAMENTO:
            self.iniciado_em = timezone.now()
        super(Entretenimento, self).save(*args, **kwargs)

entretenimentos/forms.py
from django import forms
from .models import Entretenimento

class EntretenimentoCreateForm(forms.ModelForm):
    class Meta:
        model = Entretenimento
        fields = ['tipo', 'descricao']
        widgets = {
            'tipo': forms.Select(attrs={'class': 'form-select'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control'})
        }

class EntretenimentoUpdateForm(forms.ModelForm):
    class Meta:
        model = Entretenimento
        fields = '__all__'
        
        widgets = {
            'tipo': forms.Select(attrs={'class': 'form-select'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
        }

entretenimentos/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import Entretenimento
from .forms import EntretenimentoUpdateForm, EntretenimentoCreateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def entretenimento_create(request):
    """ view que cria um entretenimento """
    if request.method == 'POST':
        form = EntretenimentoCreateForm(request.POST)
        if form.is_valid():
            entretenimento = form.save(commit=False)
            entretenimento.criado_por = request.user
            entretenimento.save()
            messages.success(request, 'Entretenimento criado com sucesso!')
            return redirect('entretenimento_create')
    else:
        form = EntretenimentoCreateForm()
    context = {
        'form': form
    }
    return render(request, 'entretenimentos/entretenimento_create.html', context)

@login_required
def entretenimento_list(request):
    """ view que exibe os entrenimentos do sistema """
    entretenimentos = Entretenimento.objects.all()
    context = {
        'entretenimentos': entretenimentos
    }
    return render(request, 'entretenimentos/entretenimento_list.html', context)

@login_required
def entretenimento_detail(request, id_entretenimento) -> HttpResponse:
    """
    Detalha o entretenimento selecionado e permite sua atualização 

    Args:
        request: O objeto HttpRequest do Django
        id_entretenimento: O id do entretenimento selecionado
    
    
    Returns:
        HttpResponse: Renderiza o template de detalhe do entretenimento
    """
    entretenimento = get_object_or_404(Entretenimento, id=id_entretenimento)
    if request.method == 'POST':
        form = EntretenimentoUpdateForm(request.POST, instance=entretenimento)
        if form.is_valid():
            form.save()
            messages.success(request, 'Entretenimento atualizado com sucesso!')
            return redirect('entretenimento_list')
    else:
        form = EntretenimentoUpdateForm(instance=entretenimento)
    context = {
        'form': form
    }
    return render(request, 'entretenimentos/entretenimento_detail.html', context)

@login_required
def entretenimento_delete(request, id_entretenimento) -> HttpResponse:
    """
    Deleta um entretenimento

    Args:
        request (_type_): O objeto HttpRequest do Django
        id_entretenimento (_type_): O id do entretenimento selecionado

    Returns:
        HttpResponse: renderiza o template entretenimento_list.html
    """
    entretenimento = get_object_or_404(Entretenimento, id=id_entretenimento)
    entretenimento.delete()
    messages.success(request, 'Entretenimento deletado com sucesso!')
    return redirect('entretenimento_list')

entretenimentos/templates/entretenimentos/entretenimento_create.html
{% extends 'base.html' %}
{% block title %}Novo Entretenimento{% endblock %}
{% block content %}
    <div>
        <a href="{% url 'entretenimento_list' %}" title="Voltar">
            <i class="botao-voltar bi bi-arrow-left-circle-fill"></i>
        </a>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <h1 class="text-center mb-4">Novo Entretenimento</h1>
            <form class="border rounded-4 p-4" action="." method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label fw-bold">
                            {{ field.label }}
                        </label>
                        {{ field }}            
                        
                        {% if field.help_text %}
                            <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

entretenimentos/templates/entretenimentos/entretenimento_detail.html
{% extends 'base.html' %}
{% block title %}Entretenimento{% endblock %}
{% block content %}
    <a href="{% url 'entretenimento_list' %}" title="Voltar" class="d-inline-block">
        <i class="botao-voltar bi bi-arrow-left-circle-fill"></i>
    </a>
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <h1 class="text-center mb-4">{{ form.instance.descricao }}</h1>
            <form method="POST" action="." class="bg-white border rounded-4 p-4 shadow-sm">
                {% csrf_token %}
                <!-- Renderizando em modo apenas leitura o campo Criado em -->
                <div class="mb-3">
                    <label for="inputCriadoEm" class="form-label fw-bold">Criado em</label>
                    <input id="inputCriadoEm" class="form-control bg-light" value="{{ form.instance.criado_em|date:"d/m/Y H:i" }}" readonly>
                </div>
                <!-- Renderizando os campos do formulário -->
                {% for field in form %}
                    <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label fw-bold">{{ field.label }}</label>
                    {{ field }}
                    </div>
                {% endfor %}
                <!-- Renderizando em modo apenas leitura o campo Iniciado em -->
                <div class="mb-3">
                    <label for="inputIniciadoEm" class="form-label fw-bold">Iniciado em</label>
                    <input id="inputIniciadoEm" class="form-control bg-light" value="{{ form.instance.iniciado_em|date:'d/m/Y H:i'|default:'' }}" readonly>
                </div>
                <!-- Renderizando em modo apenas leitura o campo finalizado em -->
                 <div class="mb-3">
                    <label for="inputFinalizadoEm" class="form-label fw-bold">Finalizado em</label>
                    <input id="InputFinalizadoEm" class="form-control bg-light" value="{{ form.instance.finalizado_em|date:'d/m/Y H:i'|default:'' }}" readonly>
                 </div>
                 <!-- Renderizando em modo apenas leitura o campo criado por -->
                  <div class="mb-3">
                    <label for="inputCriadoPor" class="form-label fw-bold">Criado por</label>
                    <input id="inputCriadoPor" class="form-control bg-light" value="{{ form.instance.criado_por.first_name }}" readonly>
                  </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

entretenimentos/templates/entretenimentos/entretenimento_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Entretenimentos{% endblock %}
{% block content %}
    <h1 class="text-center mb-4">Entretenimentos</h1>
    <div class="botao-adicao d-flex justify-content-end mb-3">
        <a class="btn btn-primary rounded-circle shadow" href="{% url 'entretenimento_create' %}" style="width: 45px; height: 45px; display: flex; align-items: center; justify-content: center;" title="Adicionar Entretenimento">
            <i class="bi bi-plus-lg" style="font-size: 1.2rem;"></i>
        </a>      
    </div>
    <table class="table table-striped table-hover align-middle">
        <thead>
            <tr>
            <th scope="col" class="d-none d-md-table-cell">Criado em</th>
            <th scope="col">Tipo</th>
            <th scope="col">Descrição</th>
            <th scope="col">Status</th>
            <th scope="col" class="d-none d-md-table-cell">Adicionado por</th>
            <th scope="col">Término</th>
            <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for entretenimento in entretenimentos %}
                <tr class="linha-click" data-href="{% url 'entretenimento_detail' entretenimento.id %}" style="cursor: pointer;">
                <th scope="row" class="d-none d-md-table-cell">{{ entretenimento.criado_em|date:"d/m/Y" }}</th>
                <td>{{ entretenimento.get_tipo_display }}</td>
                <td>{{ entretenimento.descricao }}</td>
                <td>{{ entretenimento.get_status_display }}</td>
                <td class="d-none d-md-table-cell">{{ entretenimento.criado_por.first_name }}</td>
                <td>{{ entretenimento.finalizado_em|date:"d/m/Y" }}</td>
                <td>
                    <button type="button"
                            class="btn btn-danger disable-on-submit"
                            data-bs-toggle="modal"
                            data-entretenimento-id="{{ entretenimento.id }}"
                            data-entretenimento-descricao="{{ entretenimento.descricao}}"
                            data-bs-target="#modalConfirmaExclusao"
                            title="Excluir">
                        <i class="bi bi-trash botao-acao"></i>
                    </button>
                </td>
                </tr>
            {% empty%}
                <th colspan="7" class="text-center">Não há entretenimentos cadastrados</th>
            {% endfor %}
        </tbody>
        </table>
    
    
    <!-- Estrutura do Modal -->
    <div class="modal fade" id="modalConfirmaExclusao" tabindex="-1" aria-labelledby="modalConfirmaExclusaoLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="meuModalExemploLabel">Confirmação de Exclusão</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>Confirma a exclusão do entretenimento: <span class="fw-bold" id="conteudoEntretenimento"></span></p>
        </div>
        <div class="modal-footer">
            <form method="POST" action="" id="formEntretenimentoExclusao">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Excluir</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </form>
            
        </div>
        </div>
    </div>
    </div>
    <script src="{% static 'entretenimentos/js/script.js' %}"></script>
{% endblock %}